server:
  port: 8001
mybatis:
  type-aliases-package: com.kangliuwen.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,
  instance:
    instance-id: springcloud-provider-dept8001 #修改eureka上的默认描述信息
#info配置,可以在eureka监控页面中点击id访问http://localhost:8001/actuator/info，说明这个微服务是干嘛用的
info:
  app.name: kangliuwen-springcloud
  company.name: blog.kangliuwen













